.TH POKEMON-CLI "1" "June 2016" "pokemon-cli 0.12"
.SH NAME
pokemon-cli \- a remote procedure call client for Pokemon Core. 
.SH SYNOPSIS
pokemon-cli [options] <command> [params] \- Send command to Pokemon Core. 
.TP
pokemon-cli [options] help \- Asks Pokemon Core for a list of supported commands.
.SH DESCRIPTION
This manual page documents the pokemon-cli program. pokemon-cli is an RPC client used to send commands to Pokemon Core.

.SH OPTIONS
.TP
\fB\-?\fR
Show possible options.

.SH "SEE ALSO"
\fBpokemond\fP, \fBpokemon.conf\fP
.SH AUTHOR
This manual page was written by Ciemon Dunville <ciemon@gmail.com>. Permission is granted to copy, distribute and/or modify this document under the terms of the MIT License.

The complete text of the MIT License can be found on the web at \fIhttp://opensource.org/licenses/MIT\fP.
